apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wardline.fullname" . }}-policy
  labels:
    {{- include "wardline.labels" . | nindent 4 }}
data:
  policy: |
{{ .Values.wardline.policy | indent 4 }}
