// Package adapter writes a policygen-inferred rule set to a
// policy.yaml-shaped file -- the same schema policy/adapter.LoadFile
// already parses, so the output is loadable immediately with no loader
// changes.
package adapter

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"

	policydomain "github.com/kabirnarang39/wardline/internal/features/policy/domain"
)

// Meta carries the provenance an operator needs printed above the
// generated rules: the audit range queried, how many entries fed
// inference, and how many JSONL lines were unparseable.
type Meta struct {
	From, To     time.Time
	EntryCount   int
	SkippedLines int
}

type ruleOut struct {
	Identity string `yaml:"identity"`
	Tool     string `yaml:"tool"`
	Tenant   string `yaml:"tenant,omitempty"`
	Effect   string `yaml:"effect"`
}

type policyOut struct {
	Rules   []ruleOut `yaml:"rules"`
	Default string    `yaml:"default"`
}

// WriteFile writes rules (already sorted and deduped by policygen/domain.Infer)
// as a policy.yaml-shaped file at path, preceded by a comment header
// describing where it came from and warning that it is a starting point,
// not a finished policy. default is always "deny".
//
// path is created with O_WRONLY|O_CREATE|O_EXCL, 0600 -- the same
// convention cmd/wardline/policypack.go's runPolicyPackInstallTo already
// uses for "write an operator-chosen policy file path": it refuses to
// overwrite an existing file and does not follow a dangling symlink at
// path. A failed or partial write removes whatever was created.
func WriteFile(path string, rules []policydomain.Rule, meta Meta) error {
	out := make([]ruleOut, len(rules))
	for i, r := range rules {
		out[i] = ruleOut{Identity: r.Identity, Tool: r.Tool, Tenant: r.Tenant, Effect: string(r.Effect)}
	}
	doc, err := yaml.Marshal(policyOut{Rules: out, Default: string(policydomain.EffectDeny)})
	if err != nil {
		return fmt.Errorf("marshal generated policy: %w", err)
	}

	header := fmt.Sprintf(
		"# Generated by `wardline infer-policy` from audit traffic in\n"+
			"# [%s, %s).\n"+
			"# %d distinct (tenant, identity, tool) combinations observed across %d\n"+
			"# allowed/passthrough audit entries; %d entries skipped (malformed lines).\n"+
			"#\n"+
			"# This is a STARTING POINT, not a finished policy: it allow-lists exactly\n"+
			"# what was observed and denies everything else by default. Review every\n"+
			"# rule before adopting it -- traffic you didn't want to bless is traffic\n"+
			"# this command has no way to distinguish from traffic you did.\n",
		meta.From.Format(time.RFC3339), meta.To.Format(time.RFC3339),
		len(rules), meta.EntryCount, meta.SkippedLines,
	)

	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("refusing to overwrite existing file: %s", path)
		}
		return fmt.Errorf("create %s: %w", path, err)
	}
	_, writeErr := f.Write(append([]byte(header), doc...))
	if closeErr := f.Close(); writeErr == nil {
		writeErr = closeErr
	}
	if writeErr != nil {
		_ = os.Remove(path)
		return fmt.Errorf("write %s: %w", path, writeErr)
	}
	return nil
}
